### ISSUE TITLE
Add translatable Structure Name

### ISSUE THREAD

**Issue by DRACTION** [TelepathicGrunt/WITS#2]
Hi, it would be handy if the structure name view was also displayed.

I took the representation of the structure name from the [ExplorersCompass](https://github.com/MattCzyr/ExplorersCompass/blob/forge-1.18.2/src/main/java/com/chaosthedude/explorerscompass/util/StructureUtils.java#L135) mod. As a result, we get the name of the structure in accordance with the selected language, or at least in a more or less neat form.

As an example, in my case it turned out something like this:
```java
public class WITSCommand {
    private static void listStructuresAtSpot(.....
    .....
        for (ConfiguredStructureFeature<?, ?> structure : structures) {
            ResourceLocation key = level.registryAccess().registryOrThrow(Registry.CONFIGURED_STRUCTURE_FEATURE_REGISTRY).getKey(structure);
            //++Z@RYA
            // stringBuilder.append("§r\n - §6").append(key);
            stringBuilder.append("§r\n - §6").append(key)
                .append(" §2(").append(getPrettyStructureName(key)).append(")");
            //--Z@RYA
        }

        Component component = new TextComponent(stringBuilder.toString());
        cs.getSource().sendSuccess(component, !(cs.getSource().getEntity() instanceof Player));
    }
    //++Z@RYA ExplorersCompass/src/main/java/com/chaosthedude/explorerscompass/util/StructureUtils.java
    private static String getPrettyStructureName(ResourceLocation key) {
        String name = key.toString();
        name = I18n.get(Util.makeDescriptionId("structure", key));
        if (name.equals(Util.makeDescriptionId("structure", key))) {
            name = key.toString();
            if (name.contains(":")) {
                name = name.substring(name.indexOf(":") + 1);
            }
            name = WordUtils.capitalize(name.replace('_', ' '));
        }
        return name;
    }
    //--Z@RYA
}
```

**Comment by TelepathicGrunt** [comment]
This mod wits is not for pretty translated names of structures. I wanted to show the absolute registry names of the structures. The names that show when trying to use locate command and all that because it shows the absolute modid and id of the structure. No translation issues or loss of info that could occurred there. (Also consider that vanilla clients will be using my mod so they would see the translation key instead of the translated name too…)

If you’re looking for a user friendly structure name displayed, this other mod fits that better: https://www.curseforge.com/minecraft/mc-mods/structure-credits
